import { Box, Button, Flex, Stack, Text, useMantineTheme } from '@mantine/core';
import { ClipList } from '../components/clip-list';
import { useState } from 'react';
import { useMediaQuery } from '@mantine/hooks';

export default () => {
  const [showMp4s, setShowMp4s] = useState(false);
  const [sortRecent, setSortRecent] = useState(false);

  const theme = useMantineTheme();
  const isMobile = useMediaQuery(`(max-width: ${theme.breakpoints.md})`);

  return (
    <Box mx="auto" maw="calc(1200px + 6.75rem)">
      <Stack m="xl">
        <Flex
          justify="space-between"
          align="center"
          mb="lg"
          gap="lg"
          direction={isMobile ? 'column' : undefined}
        >
          <Flex direction="column" w="100%" style={{ flexShrink: 1 }}>
            <Text component="h1" size="2rem" my={0}>
              Browse
            </Text>
            <Text size="md" color="dimmed">
              View GIFs and MP4s generated by other users
            </Text>
          </Flex>
          <Flex
            gap="md"
            direction={isMobile ? 'column' : undefined}
            justify={isMobile ? undefined : 'flex-end'}
            w="100%"
          >
            <Flex align="center" justify="space-between" gap="md">
              <Text>Show as</Text>
              <Button.Group>
                <Button
                  variant={showMp4s ? 'default' : 'filled'}
                  onClick={() => setShowMp4s(false)}
                >
                  GIFs
                </Button>
                <Button
                  variant={showMp4s ? 'filled' : 'default'}
                  onClick={() => setShowMp4s(true)}
                >
                  MP4s
                </Button>
              </Button.Group>
            </Flex>
            <Flex align="center" justify="space-between" gap="md">
              <Text>Sort by</Text>
              <Button.Group>
                <Button
                  variant={sortRecent ? 'default' : 'filled'}
                  onClick={() => setSortRecent(false)}
                >
                  Popularity
                </Button>
                <Button
                  variant={sortRecent ? 'filled' : 'default'}
                  onClick={() => setSortRecent(true)}
                >
                  Most recent
                </Button>
              </Button.Group>
            </Flex>
          </Flex>
        </Flex>
        <ClipList
          filetype={showMp4s ? 'mp4' : 'gif'}
          sort={sortRecent ? 'recent' : 'popular'}
        />
      </Stack>
    </Box>
  );
};
