import { Box, Stack, Text } from '@mantine/core';
import { SnippetList } from '../components/snippet-list';

export default () => {
  return (
    <Box mx="auto" maw="calc(1200px + 6.75rem)">
      <Stack m="xl">
        <Text component="h1" size="2rem" mb="-lg">
          Snippets
        </Text>
        <Text size="md" color="dimmed">
          View premade GIF and MP4 snippets generated by other users
        </Text>
        <SnippetList />
      </Stack>
    </Box>
  );
};
