const quotes = [
  'Why do people run from me?',
  "Me fail English? That's unpossible!",
  'I am the lizard queen!',
  'Hi, Lisa. Hi, Supernintendo Chalmers.',
  'Aw, twenty dollars? I wanted a peanut!',
  "Please don't tell anyone how I live",
  "Hello, Smithers. You're quite good... at turning... me on",
  "Attention, Marge Simpson, your son has been arrested. [...] We've also arrested your older, balder, fatter son.",
  'what do you say we go out for a round of frosty chocolate milkshakes?',
  'Nobody snuggles with Max Power. You strap yourself in and feel the Gs!',
  '"Gym"? What\'s a "gym"?',
  '-What is it? -"Tramampoline!" "Trambapoline!"',
  'Whoo-hoo! Look at that blubber fly',
  "If I could just say a few words... I'd be a better public speaker",
  'Mrs. Krabappel and Principal Skinner were in the closet making babies, and I saw one of the babies, and the baby looked at me.',
  '"I engaged in intercourse with your spouse or significant other. Now, that\'s psychiatry!',
  'I wonder what my life would be like if I robbed the Kwik-E-Mart...',
  'So I tied an onion to my belt, which was the style at the time.',
  'I call the big one Bitey',
  "You didn't do anything. (chuckles) Didn't I?",
  "I'm going outside... to... stalk... Lenny and Carl... D'oh!",
  'In America, first you get the sugar, then you get the power, then you get the women.',
  'I know you can read my thoughts, boy. ♪ Meow meow meow meow meow meow meow meow ♪ ♪ Meow meow meow meow meow meow meow meow ♪',
  "I'm not a state! I'm a monster!",
  "Here's a little trick to help you remember. If it's clear and yella, you've got juice there, fella. If it's tangy and brown, you're in cider town.",
  "The sum of the square roots of any two sides of an isosceles triangle is equal to the square root of the remaining side. -That's a right triangle, ya idiot! -D'oh!",
  "Geez, Homer, I thought someone with two wives would be happy. No, you're thinking of someone with two knives. I got to tell you, this is pretty terrific.",
  '"Le grille"? What the hell is that?',
  'Good Lord! What is happening in there? Aurora borealis. Aurora borealis?! At this time of year, at this time of day, in this part of the country, localized entirely within your kitchen? -Yes. -May I see it? No.',
];

export const randomQuote = () =>
  quotes[Math.floor(Math.random() * quotes.length)];
