name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --force

      - name: Build project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: simpsons-gif-generator-build
          path: |
            dist/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: simpsons-gif-generator-build

      - name: Deploy files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "dist/*"
          target: "web/www/simpsons"
          overwrite: true
